import { ThemeProvider } from "@/context/ThemeContext";
import "./globals.css";

export const metadata = {
  title: "Talent Trail | Job Board Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <html lang="en">
        <link rel="icon" href="/favicon.svg" sizes="any" />
        <body>{children}</body>
      </html>
    </ThemeProvider>
  );
}
